#!/bin/bash

# examples:
# makeOrbOrder 8Ag 19B1g scf_out.dat
# makeOrbOrder 8Ag 14B3u scf_out.dat

# global variables
ME=$(basename "$0")
SYNTAX="${ME} START END FILE"
UNREAD="${ME}: could not read file:"

# evaluate the arguments
if [ ${#} -ne 2 -a ${#} -ne 3 ]
then
  echo "${SYNTAX}" 1>&2
  exit 1
else
  START="$1"
  END="$2"
  SCFOUT="${3:--}"
  if [ ! -r "${SCFOUT}" -a "${SCFOUT}" != '-' ]
    then
    echo "${UNREAD} ${SCFOUT}" 1>&2
  fi
fi

# do the actual filtering
cat "${SCFOUT}" | sed -n "/Orbital Energies \[Eh\]/,/Final Occupation by Irrep/p" |
  head -n-2 | sed 's/ *//' | sed -r 's/([0-9]{2,} +)([0-9])/\1\n\2/g' |
  sed -r 's/^[^0-9]+/# &/' | grep -v '^ *$' | sed 's/ *$//' | grep -vi 'virtual' |
  sed -ne "/$START/,$ p" | sed "/$END/q" | cut -d' ' -f1 |
  sed 's/\(^[0-9]*\)\(.*\)/\2:\1/'

