#!/bin/bash

for i in 1.68 1.69 1.70 1.71 1.72; do
    Eval=$(cat "${i}"/dmrg/Ag0/dmrg.out |
      grep 'Minimum energy encountered during all instructions'|
      tail -n1 | egrep -o '[^ ]*$')
    Rval=${i}
    echo -e "${Rval}\t${Eval}"
done
